container_name: {{ cookiecutter.service_name }}
build:
  context: {{ cookiecutter.service_name }}
  dockerfile: Dockerfile
image: {{ 'img_' + cookiecutter.service_name }}
user: "{{ cookiecutter.uid }}"
network_mode: host
entrypoint: /usr/local/bin/python
command:
  - -u
  - client.py
  - --url={{ cookiecutter.url }}
  - --realm={{ cookiecutter.realm }}
  - --service_name={{ cookiecutter.service_name }}
  - --service_uuid={{ cookiecutter.service_uuid }}
