container_name: {{ cookiecutter.service_name }}
build:
  context: {{ cookiecutter.service_name }}
  dockerfile: Dockerfile
image: {{ 'img_' + cookiecutter.service_name }}
user: "{{ cookiecutter.uid }}"
network_mode: host
entrypoint: /client
command:
  - "127.0.0.1"
  - "8080"
